services:
  # PostgreSQL database
  postgres:
    image: postgres:16
    container_name: underwatch_backend
    environment:
      POSTGRES_DB: underwatch_database
      POSTGRES_USER: underwatch
      POSTGRES_PASSWORD: underwatch
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5433:5432"
    volumes:  #for the example data import
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql