	zmv '(*)_vorneLaufen(*).png' '$1_walk_front_$2.png'
	zmv '(*)_rechtsLaufen(*).png' '$1_walk_right_$2.png'
	zmv '(*)_linksLaufen(*).png' '$1_walk_left_$2.png'
	zmv '(*)_hintenLaufen(*).png' '$1_walk_back_$2.png'
	zmv '(*)_vorneSitzen(*).png' '$1_idle_front_$2.png'
	zmv '(*)_hintenSitzen(*).png' '$1_idle_back_$2.png'
	zmv '(*)_linksSitzen(*).png' '$1_idle_left_$2.png'
	zmv '(*)_rechtsSitzen(*).png' '$1_idle_right_$2.png'
