# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: React CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'website/**'
      - '.github/workflows/react.yaml'

permissions:
  contents: read


jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v3
        - name: Use Node.js 18.x
          uses: actions/setup-node@v2
          with:
            node-version: 18.x
        - name: Install dependencies
          run: npm install
          working-directory: website
        - name: Run Tests
          run: npm test
          working-directory: website
        - name: Generate build
          run: npm run build
          working-directory: website
        - name: Log in to the Container registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: https://ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}  
        - name: Build and push Docker image
          uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
          with:
            context: ./website/
            file: ./website/Dockerfile
            push: true 
            tags: ghcr.io/se-tinf22b6/underwatch/website:${{ github.sha }}, ghcr.io/se-tinf22b6/underwatch/website:latest